#!/bin/bash

echo "======================="
echo " RAPPEL DES COMMANDES:"
echo "======================="
echo ""
echo "sudo systemctl <arg> NetworkManager.service"
echo "      <arg> = status, restart, start, enable, disable"
echo ""
echo "lister connections"
echo "      nmcli d wifi list"
echo ""
echo "ajouter connection"
echo "      nmcli dev wifi connect <SSID> password <password>"
echo "      <SSID> et <password> avec des guillemets? (pas sûr lol)"
echo ""
echo "reconnecter à une connection"
echo "      nmcli con up <SSID>"
echo ""
echo "supprimer connection:"
echo "      nmcli con delete <SSID>"
echo ""
echo "on/off:"
echo "      nmcli r wifi off"
echo "      nmcli r wifi on"
echo "ça peut marcher quand ça déconne"
