spec "core.colorscheme.gruvbox"
-- spec "core.colorscheme.kanagawa"
spec "core.colorscheme.tokyonight"
-- spec "core.colorscheme.molokai"
-- spec "core.colorscheme.flexoki"
-- spec "core.colorscheme.molokayo"
-- spec "core.colorscheme.monokai-pro"
-- spec "core.colorscheme.monokai"
-- spec "core.colorscheme.cyberdream"
-- spec "core.colorscheme.lackluster"
-- spec "core.colorscheme.boring"
-- spec "core.colorscheme.zazen"
-- spec "core.colorscheme.tender"
-- spec "core.colorscheme.darkplus"
-- spec "core.colorscheme.yorumi"
-- spec "core.colorscheme.lighthaus"
-- spec "core.colorscheme.onedarkpro"
-- spec "core.colorscheme.biscuit"
-- spec "core.colorscheme.newpaper"
-- spec "core.colorscheme.github-theme"
-- spec "core.colorscheme.material"
spec "core.colorscheme.solarized"
-- spec "core.colorscheme.base16"
-- spec "core.colorscheme.nightfox"
-- spec "core.colorscheme.moonfly"
-- spec "core.colorscheme.noirbuddy"
-- spec "core.colorscheme.vscode"
